openapi: 3.2.0
info:
  title: Vault Notifications API
  version: 1.35.0
  x-logo:
    url: https://www.ledger.com/wp-content/themes/ledger-v2/public/images/ledger-logo-long.svg
  description: '# Authentication


    The Ledger Vault API offers several methods of authentication.'
security:
- Ledger_API_User: []
- Ledger_API_User: []
  Ledger_API_Key: []
- Ledger_API_User: []
  Ledger_Store_Auth_Token: []
- Ledger_API_User: []
  Ledger_API_Key: []
  Ledger_Store_Auth_Token: []
tags:
- description: 'The notification feature allows you to be notified when an API user

    receives an important event.'
  name: Notifications
paths:
  /notifications/configuration:
    get:
      summary: Get notification configuration
      tags:
      - Notifications
      description: This method returns the notification configuration set for the current user.
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Configuration'
          description: Current user notification configuration
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Current user doesn't have any configuration
      operationId: getNotificationsConfiguration
      x-operation-id-source: derived
    put:
      summary: Set notification configuration
      tags:
      - Notifications
      description: This method allows you to set the notification configuration for the current user.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Configuration'
        description: Configuration to create
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Configuration'
          description: Current user notification configuration
      operationId: putNotificationsConfiguration
      x-operation-id-source: derived
components:
  schemas:
    Error:
      properties:
        message:
          type: string
        name:
          type: string
        status_code:
          type: integer
      required:
      - message
      - name
      - status_code
      type: object
    Webhook:
      properties:
        secret:
          description: shared secret for webhook signature check
          example: topsecret
          type: string
        url:
          description: webhook url, https only
          example: https://vault.crypstock.com/webhook
          format: url
          type: string
      required:
      - secret
      - url
      type: object
    ConfigurationProfile:
      properties:
        webhook:
          allOf:
          - $ref: '#/components/schemas/Webhook'
          default: null
          description: webhook to be notified on
      type: object
    Configuration:
      properties:
        all:
          allOf:
          - $ref: '#/components/schemas/ConfigurationProfile'
          description: configuration for all kind of notifications
      required:
      - all
      type: object
  securitySchemes:
    Ledger_API_User:
      description: (**required**) Username of a registered API User
      in: header
      name: X-Ledger-API-User
      type: apiKey
    Ledger_API_Key:
      description: If you've set up your API Key when initializing your LAM, you'll need to include it as a header along with the api user header. For more details, [see step 5 of the get started documentation](https://help.vault.ledger.com/Content/api/api_getstarted.html).
      in: header
      name: X-Ledger-API-Key
      type: apiKey
    Ledger_Store_Auth_Token:
      description: If you've set up HashiCorp Vault as an authentication service, you'll need to pass the `X-Ledger-Store-Auth-Token` header along with the API user header. For more details see [how to set up HashiCorp Vault with the LAM](https://help.vault.ledger.com/Content/api/hashicorp_vault.html).
      in: header
      name: X-Ledger-Store-Auth-Token
      type: apiKey
